<?php 

"CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password varchar(255) NOT NULL,
    otp VARCHAR default 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP 
)";

"CREATE TABLE task (
    id INT AUTO_INCREMENT PRIMARY KEY,
    description text NOT NULL,
    status VARCHAR(255) NOT NULL UNIQUE,
    password varchar(255) NOT NULL,
    otp VARCHAR default 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP 
)";